# Prerequisites
  -  name: Adding the EPEL Repository to Compute (CentOS)
     yum:
       name:
         -  epel-release
         -  python34
         -  python-devel
         -  gcc
       state: present

  -  name: Enabling EPEL Repository in Compute (CentOS)
     ini_file:
       dest: /etc/yum.repos.d/epel.repo
       section: epel
       option: enabled
       value: 1

  -  name: Reload Packages (CentOS)
     yum:
       name: "*"
       state: latest

